version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-api
    ports:
      - "3333:333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apivendas
      - PGPORT=5432

  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: apivendas-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAUT_EMAIL=admin@admin.com
      - PGADMIN_DEFAUT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
